### ISSUE TITLE
Where can I find API reference documentation?

### ISSUE THREAD

**Issue by jeffcharles** [ppatierno/m2mqtt#10]
I'm having trouble locating where the API reference documentation is hosted (assuming it exists). That is to say, documentation that lists out the public classes/interfaces and the public method signatures with descriptions of what they do.

I've looked at <https://m2mqtt.wordpress.com/> and on the GitHub wiki with no luck. So far I've been using the source code as a reference but it's not nearly as easy to consume as hyperlinked documentation, especially with the broker interface mixed in with the client source code.

**Comment by ppatierno** [comment]
Hi,
On that web site under "Documentation -> M2Mqtt Client" you can find APIs information.

Paolo.

**Comment by jeffcharles** [comment]
I'm looking at that page and all of the other ones located under it. That page just has building the source code, ssl/tls support, and example. I don't see any API reference documentation.

The Using MqttClient page also just has code examples, no reference docs.

**Comment by ppatierno** [comment]
Oh yes an APIs reference as you said doesn't exist for now.

**Comment by leandroMsouza** [comment]
Paul, exist any example how to open and MQTTClient and Broker on some machine?
