### ISSUE TITLE
Support of self-signed certificates

### ISSUE THREAD

**Issue by AOlefirenko** [ppatierno/m2mqtt#12]
Hello. Are there any plans to support self-signed certificates? I'm looking for opportunity to connect my application to AWS IoT. For now there is official sdk only for both node.js and C Embedded..

**Comment by andr3at** [comment]
Hello. I would like to use m2mqtt client to connect my .NET app to AWS IoT, but AWS IoT MQTT broker requires mutual authentication, not supported by m2mqtt client so far. Is there any plan to implement mutual authentication support on m2mqtt? Many Thanks

**Comment by ppatierno** [comment]
Hi,
the current repository has a "develop" branch with this feature. Up to now I had no time to test it so your contribution in that sense could be great.

Paolo.

**Comment by AOlefirenko** [comment]
@ppatierno Thank you! I will test it

**Comment by andr3at** [comment]
Thanks a lot! I will test and provide feedback

**Comment by AOlefirenko** [comment]
@andr3at @ppatierno  I've tried to build from the develop branch. It works when I use X509Certificate2 and pfx file that I created from .cer certificate and private key. I think it would be great to implement overload that accepts client certificate and private key separately. How do you find it?

**Comment by andr3at** [comment]
@AOlefirenko @ppatierno  That's a very good new! I was struggling against the same issue: how to use certificate and private key at the same time. By the way, could you please elaborate on what you have done? At present I have three files: rootCA.pem, cert.pem and thing-private-key.pem which are the ones I use to access AWS IoT through mosquitto client and CLI. How to get a pfx file? Sorry, I'm not very familiar with certificates.Thanks a lot!

**Comment by AOlefirenko** [comment]
@andr3at You need openssl. Look at http://stackoverflow.com/questions/6307886/how-to-create-pfx-file-from-cer-certificate-and-private-key

**Comment by ppatierno** [comment]
@AOlefirenko it's a great news ! Did you try to connect with AWS IoT ?

**Comment by AOlefirenko** [comment]
@AOlefirenko Yes. It works pretty good!  I've found solution for dealing with a private key. Would you like use it in your project?
http://stackoverflow.com/questions/18462064/associate-a-private-key-with-the-x509certificate2-class-in-net

**Comment by ppatierno** [comment]
It's a great news for me ! Thanks @AOlefirenko ! 

I'll take a look at your links.
However I can merge the develop branch to the master in the next days.

Do you have a blog ? Will you write something about this M2Mqtt usage with AWS IoT ?

**Comment by AOlefirenko** [comment]
Unfortunately I have no blog yet. I'm newbie in IoT world. But it seems I MUST promote this project anyway.=) It's definitely great work! It really helped me

**Comment by ppatierno** [comment]
Great ! I'm happy to know about that .. I need to create an AWS IoT account and write something about it ... thanks for your test ;-)

**Comment by andr3at** [comment]
@AOlefirenko Thanks for the link provided. Looks like my m2mqtt client is connecting correctly to aws iot (at least I have no exceptions) but any message it published is not received by the m2mqtt subscriber. Do you have evidence that messages are correctly published on AWS IoT broker and/or received by subscribers? Thanks

**Comment by adrenalinehit** [comment]
I can also confirm that I can connect using the pfx X509Certificate2 type to AWS IoT.  Great work, thanks @ppatierno and @AOlefirenko

**Comment by andr3at** [comment]
@adrenalinehit Can you confirm that messages are correctly published on AWS IoT broker and received by subscribers? I can connect with a publisher client1 and a subscriber client2. But if the publisher client1 publishes a message on topic A, then the subscriber client2 does not receive the same message on topic A. Did you try message pub/sub like that one? Thanks

**Comment by adrenalinehit** [comment]
@andr3at yes I did try pub/sub - a simple .net console app subscribing to 1) the exact topic and 2) a wildcard topic.  It wasn't extensive testing but it did work.  Check that the topic that you're publishing to and the one you're subscribing too match exactly.  (The wildcard option can be specified using a # rather than a *)  In both cases, my rule in AWS IoT was executed as well - i.e. the published message ended up in my dynamodb table as well.

**Comment by andr3at** [comment]
@adrenalinehit Thank you very much for your confirmation. That means I'm doing something wrong. I did check that pub and sub use exactly the same topic but looks the issue is elsewhere. I will try again asap and let you know.

**Comment by adrenalinehit** [comment]
Feel free to share some code @andr3at or logs, and I could take a look as well?

**Comment by adrenalinehit** [comment]
@andr3at - one further thing, i'm using MqttMsgBase.QOS_LEVEL_AT_LEAST_ONCE when I subscribe.

**Comment by ppatierno** [comment]
@adrenalinehit ... could you interested in writing a brief article on your sample application to publish as use case in the official M2Mqtt web site ? It could be great to share how it's simple to connect M2Mqtt top AWS IoT.

**Comment by andr3at** [comment]
@adrenalinehit Looks like the issue was exactly on MqttMsgBase.QOS_LEVEL_AT_LEAST_ONCE, as you pointed out. I was using MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE instead. I've done just a couple of quick trials but looks like subscriber client get the messages. I will come back with a more accurate feedback as soon as I will do more test. Thanks a lot for your precious support!

**Comment by adrenalinehit** [comment]
@ppatierno - I don't have a personal blog, but might be able to get something published through my corporate blog in the new year.  I'll put my source on github once I've sanitised it.

@andr3at  - glad you managed to get it working. :-) you're welcome.

**Comment by adrenalinehit** [comment]
@ppatierno - no blog post, but some gists:

*Publisher:
https://gist.github.com/adrenalinehit/a4e2684a0b3b0a49b48e#file-mqtt-publisher-cs

*Subscriber:
https://gist.github.com/adrenalinehit/ccfeba90264a02fb629f#file-mqtt-subscriber-cs

*Openssl magic:
https://gist.github.com/adrenalinehit/b33994a4d430b26747ac#file-converting-to-pfx-using-openssl

**Comment by ppatierno** [comment]
@adrenalinehit great gists but without an article aren't useful to more people who don't know how to use AWS IoT. For this reason I was thinking about official M2Mqtt web site where you could write the article :-)

**Comment by adrenalinehit** [comment]
@ppatierno OK, I'd be up for that. How would you like it submitting?

**Comment by ppatierno** [comment]
@adrenalinehit can you write an Office Word document and send me to my email address ?

**Comment by AdamQ91** [comment]
Hi All, 

I followed the write up provided for M2Mqtt, and for the most part it seems to be working properly for me. I'm attempting to send messages to a DynamoDB table, but to no avail I can't get this working..

Do I need to have my "subscribe" code running in the background while my publisher code is running? 

Thanks!

**Comment by andr3at** [comment]
@AdamQ91 If I understand well you need to send data to DynamoDB. This is out of scope of M2Mqtt client lib. You can use M2Mqtt publisher just to publish data to AWS IoT mqtt broker. Then if you want to extract data from the queue and send them to DynamoDB you need to create an AWS rule, as specified by AWS developer guide (e.g. SaveDataToDynamoDB rule).
