### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by mwallnoefer** [ppatierno/m2mqtt#13]
README states:

> Following an example of client publisher to a topic :

```
... 

// create client instance 
MqttClient client = new MqttClient(IPAddress.Parse(MQTT_BROKER_ADDRESS)); 

string clientId = Guid.NewGuid().ToString(); 
client.Connect(clientId); 

string strValue = Convert.ToString(value); 

// publish a message on "/home/temperature" topic with QoS 2 
client.Publish("/home/temperature", Encoding.UTF8.GetBytes(strValue), MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE); 

...
```
client.Publish() does not contain anymore three arguments, but apparently a fourth has been added ("retain"). Maybe correct it into?
> client.Publish("/home/temperature", Encoding.UTF8.GetBytes(strValue), MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, true);

**Comment by ppatierno** [comment]
Yes you're right. Fixed. Thanks.
