### ISSUE TITLE
Broker port

### ISSUE THREAD

**Issue by smashpl** [ppatierno/m2mqtt#27]
Is there way to set broker port other than default ?
I see contructor with port parameter, but I would like to use no secure connection.
Something like this
`MqttClient client = new MqttClient("m21.cloudmqtt.com",14069,false, MqttSslProtocols.None,null);`
  
cannot be resolved .

**Comment by darekzuk** [comment]
for platform x64 (Win7) following works: 
new MqttClient("FQDN", ServerPort, false, null, MqttSslProtocols.None);

**Comment by smashpl** [comment]
Thanks Darek ! 
This worked for me
` new MqttClient("FQDN", Serverport, false, null, null, MqttSslProtocols.None);
`
