### ISSUE TITLE
messages duplicated in inflightQueue when client is disconnected

### ISSUE THREAD

**Issue by salmanebah** [ppatierno/m2mqtt#3]
Is it an intended behavior to duplicate messages in the in flight queue when the client is disconnected? 
suppose the following scenario:
  ```csharp
        var c = new MqttClient(BROKER_ADDRESS);
        c.Connect(MY_ID, null, null, false, KEEP_ALIVE);
        c.Publish("demo/test", Encoding.UTF8.GetBytes("Hi"),
                         MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, false);
        c.Disconnect();
        c.Publish("demo/test", Encoding.UTF8.GetBytes("Hi"),
                               MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, false);
```
What happens internally after the last line is that:
 The message is added in the `session` persistence **AND** the `inflightQueue` queue.
Now if the client reconnects back with: 
```csharp
    c.Connect(MY_ID, null, null, false, KEEP_ALIVE);
```
 what happens internally is that the `RestoreSession()` method is called which has the effect of adding the message previously stored in the session to the queue, as a result, the message is duplicated in the `inflightQueue` queue.

**Comment by ppatierno** [comment]
It's not a duplicate message. Each message has a unique Message Id assigned when you call Publish(). You are sending two different messages but with same payload so no duplication.
If it's a duplication for you ... it depends only on your application so it's an application layer problem.
From the MQTT client point of view the above are two different messages. The client doesn't is payload agnostic ... two messages with same payload ... are different messages.
